Class {
	#name : #XMIATestModel,
	#superclass : #MooseModel,
	#category : #'XMI-Analyzer-Tests-Entities-Model'
}

{ #category : #accessing }
XMIATestModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
XMIATestModel class >> annotation [
	<FMClass: #XMIATestModel super: #MooseModel>
	<package: #'XMI-Analyzer-Tests-Entities'>
	<generated>
]
